export interface FilterOption {
  code: string;
  name: string;
}

export const mentalHealthFilters: Record<string, FilterOption[]> = {
  "Type of Care": [
    { code: "SA", name: "Substance use treatment" },
    { code: "MH", name: "Mental health treatment" },
    { code: "SUMH", name: "Treatment for co-occurring substance use plus serious mental health illness" },
  ],
  "Service Setting": [
    { code: "HI", name: "Hospital inpatient/24-hour hospital inpatient" },
    { code: "OP", name: "Outpatient" },
    { code: "PHDT", name: "Partial hospitalization/day treatment" },
    { code: "RES", name: "Residential/24-hour residential" },
  ],
  "Facility Type": [
    { code: "CMHC", name: "Community mental health center" },
    { code: "CBHC", name: "Certified Community Behavioral Health Clinic" },
    { code: "MSMH", name: "Multi-setting mental health facility" },
    { code: "OMH", name: "Outpatient mental health facility" },
    { code: "ORES", name: "Other residential treatment facility" },
    { code: "PH", name: "Partial hospitalization/day treatment" },
    { code: "PSY", name: "Psychiatric hospital" },
    { code: "RTCA", name: "Residential treatment center (RTC) for adults" },
    { code: "RTCC", name: "Residential treatment center (RTC) for children" },
    { code: "IPSY", name: "Separate inpatient psychiatric unit of a general hospital" },
    { code: "SHP", name: "State hospital" },
    { code: "VAHC", name: "Veterans Affairs Medical Center or other VA healthcare facility" },
  ],
  "Treatment Approaches": [
    { code: "AT", name: "Activity therapy" },
    { code: "CBT", name: "Cognitive behavioral therapy" },
    { code: "CRT", name: "Cognitive remediation therapy" },
    { code: "CFT", name: "Couples/family therapy" },
    { code: "DBT", name: "Dialectical behavior therapy" },
    { code: "ECT", name: "Electroconvulsive therapy" },
    { code: "EMDR", name: "Eye Movement Desensitization and Reprocessing therapy" },
    { code: "GT", name: "Group therapy" },
    { code: "IDD", name: "Integrated Mental and Substance Use Disorder treatment" },
    { code: "IPT", name: "Individual psychotherapy" },
    { code: "KIT", name: "Ketamine Infusion Therapy" },
    { code: "TMS", name: "Transcranial Magnetic Stimulation" },
    { code: "TELE", name: "Telemedicine/telehealth therapy" },
    { code: "AIM", name: "Abnormal involuntary movement scale" },
  ],
  "Pharmacotherapies": [
    { code: "CHLOR", name: "Chlorpromazine" },
    { code: "DROPE", name: "Droperidol" },
    { code: "FLUPH", name: "Fluphenazine" },
    { code: "HALOP", name: "Haloperidol" },
    { code: "LOXAP", name: "Loxapine" },
    { code: "PERPH", name: "Perphenazine" },
    { code: "PIMOZ", name: "Pimozide" },
    { code: "PROCH", name: "Prochlorperazine" },
    { code: "THIOT", name: "Thiothixene" },
    { code: "THIOR", name: "Thioridazine" },
    { code: "TRIFL", name: "Trifluoperazine" },
    { code: "ARIPI", name: "Aripiprazole" },
    { code: "ASENA", name: "Asenapine" },
    { code: "BREXP", name: "Brexpiprazole" },
    { code: "CARIP", name: "Cariprazine" },
    { code: "CLOZA", name: "Clozapine" },
    { code: "ILOPE", name: "Iloperidone" },
    { code: "LURAS", name: "Lurasidone" },
    { code: "OLANZ", name: "Olanzapine" },
    { code: "OLANZF", name: "Olanzapine/Fluoxetine combination" },
    { code: "PALIP", name: "Paliperidone" },
    { code: "QUETI", name: "Quetiapine" },
    { code: "RISPE", name: "Risperidone" },
    { code: "ZIPRA", name: "Ziprasidone" },
    { code: "NRT", name: "Nicotine replacement" },
    { code: "NSC", name: "Non-nicotine smoking/tobacco cessation" },
    { code: "ANTPYCH", name: "Antipsychotics used in treatment of SMI" },
  ],
  "Emergency Services": [
    { code: "CIT", name: "Crisis intervention team" },
    { code: "PEON", name: "Psychiatric emergency onsite services" },
    { code: "PEOFF", name: "Psychiatric emergency mobile/off-site services" },
    { code: "WI", name: "Psychiatric emergency walk-in services" },
  ],
  "Facility Operation": [
    { code: "DDF", name: "Department of Defense" },
    { code: "LCCG", name: "Local, county, or community government" },
    { code: "IH", name: "Indian Health Services" },
    { code: "PVTP", name: "Private for-profit organization" },
    { code: "PVTN", name: "Private non-profit organization" },
    { code: "STG", name: "State government" },
    { code: "TBG", name: "Tribal government" },
    { code: "FED", name: "Federal Government" },
    { code: "VAMC", name: "U.S. Department of Veterans Affairs" },
  ],
  "Licenses/Certs": [
    { code: "FQHC", name: "Federally Qualified Health Center" },
    { code: "MHC", name: "Mental health clinic or mental health center" },
  ],
  "Payment Accepted": [
    { code: "CLF", name: "County or local government funds" },
    { code: "CMHG", name: "Community Mental Health Block Grants" },
    { code: "CSBG", name: "Community Service Block Grants" },
    { code: "FG", name: "Federal Grants" },
    { code: "ITU", name: "IHS/Tribal/Urban (ITU) funds" },
    { code: "MC", name: "Medicare" },
    { code: "MD", name: "Medicaid" },
    { code: "MI", name: "Federal military insurance (e.g., TRICARE)" },
    { code: "OSF", name: "Other State funds" },
    { code: "PI", name: "Private health insurance" },
    { code: "PCF", name: "Private or Community foundation" },
    { code: "SCJJ", name: "State corrections or juvenile justice funds" },
    { code: "SEF", name: "State education agency funds" },
    { code: "SF", name: "Cash or self-payment" },
    { code: "SI", name: "State-financed health insurance plan other than Medicaid" },
    { code: "SMHA", name: "State mental health agency funds" },
    { code: "SWFS", name: "State welfare or child and family services funds" },
    { code: "VAF", name: "U.S. Department of VA funds" },
  ],
  "Payment Assistance": [
    { code: "PA", name: "Payment assistance (check with facility for details)" },
    { code: "SS", name: "Sliding fee scale (fee is based on income and other factors)" },
  ],
  "Special Programs": [
    { code: "TAY", name: "Young adults" },
    { code: "SE", name: "Seniors or older adults" },
    { code: "GL", name: "LGBTQ+" },
    { code: "VET", name: "Veterans" },
    { code: "ADM", name: "Active duty military" },
    { code: "MF", name: "Members of military families" },
    { code: "CJ", name: "Criminal justice/Forensic clients" },
    { code: "CO", name: "Clients with co-occurring mental and substance use disorders" },
    { code: "HV", name: "Clients with HIV or AIDS" },
    { code: "DV", name: "Clients who have experienced intimate partner violence" },
    { code: "TRMA", name: "Clients who have experienced trauma" },
    { code: "TBI", name: "Persons with traumatic brain injury (TBI)" },
    { code: "ALZ", name: "Persons with Alzheimer's or dementia" },
    { code: "PED", name: "Persons with eating disorders" },
    { code: "PEFP", name: "Persons experiencing first-episode psychosis" },
    { code: "PTSD", name: "Persons with post-traumatic stress disorder (PTSD)" },
    { code: "SED", name: "Children/adolescents with serious emotional disturbance (SED)" },
    { code: "SMI", name: "Persons 18 and older with serious mental illness (SMI)" },
  ],
  "Assessment": [
    { code: "STU", name: "Screening for tobacco use" },
  ],
  "Testing": [
    { code: "HIVT", name: "HIV testing" },
    { code: "STDT", name: "STD testing" },
    { code: "TBS", name: "TB screening" },
    { code: "MST", name: "Metabolic syndrome monitoring" },
    { code: "HBT", name: "Testing for Hepatitis B (HBV)" },
    { code: "HCT", name: "Testing for Hepatitis C (HCV)" },
    { code: "LABT", name: "Laboratory testing" },
  ],
  "Ancillary Services": [
    { code: "HS", name: "Housing services" },
    { code: "PEER", name: "Mentoring/peer support" },
    { code: "TCC", name: "Smoking/vaping/tobacco cessation counseling" },
    { code: "ACT", name: "Assertive community treatment" },
    { code: "AOT", name: "Assisted Outpatient Treatment" },
    { code: "CDM", name: "Chronic disease/illness management" },
    { code: "COOT", name: "Court-ordered outpatient treatment" },
    { code: "DEC", name: "Diet and exercise counseling" },
    { code: "FPSY", name: "Family psychoeducation" },
    { code: "ICM", name: "Intensive case management" },
    { code: "IMR", name: "Illness management and recovery" },
    { code: "LAD", name: "Legal advocacy" },
    { code: "PRS", name: "Psychosocial rehabilitation services" },
    { code: "SEMP", name: "Supported employment" },
    { code: "SH", name: "Supported housing" },
    { code: "TPC", name: "Therapeutic foster care" },
    { code: "VRS", name: "Vocational rehabilitation services" },
    { code: "CM", name: "Case management service" },
    { code: "IPC", name: "Integrated primary care services" },
    { code: "SPS", name: "Suicide prevention services" },
    { code: "ES", name: "Education services" },
  ],
  "Age Groups": [
    { code: "CHLD", name: "Children/Adolescents" },
    { code: "YAD", name: "Young Adults" },
    { code: "ADLT", name: "Adults" },
    { code: "SNR", name: "Seniors" },
  ],
  "Language Services": [
    { code: "SP", name: "Spanish" },
    { code: "AH", name: "Sign language services for the deaf and hard of hearing" },
    { code: "NX", name: "American Indian or Alaska Native languages" },
    { code: "FX", name: "Other languages (excluding Spanish)" },
    { code: "F4", name: "Arabic" },
    { code: "F17", name: "Chinese (any dialect)" },
    { code: "F19", name: "Creole" },
    { code: "F25", name: "Farsi" },
    { code: "F28", name: "French" },
    { code: "F30", name: "German" },
    { code: "F31", name: "Greek" },
    { code: "F35", name: "Hebrew" },
    { code: "F36", name: "Hindi" },
    { code: "F37", name: "Hmong" },
    { code: "F42", name: "Italian" },
    { code: "F43", name: "Japanese" },
    { code: "F47", name: "Korean" },
    { code: "F66", name: "Polish" },
    { code: "F67", name: "Portuguese" },
    { code: "F70", name: "Russian" },
    { code: "F81", name: "Tagalog" },
    { code: "F92", name: "Vietnamese" },
    { code: "N24", name: "Ojibwa" },
    { code: "N40", name: "Yupik" },
  ],
  "Smoking Policy": [
    { code: "SMON", name: "Smoking not permitted" },
    { code: "SMOP", name: "Smoking permitted without restriction" },
    { code: "SMPD", name: "Smoking permitted in designated area" },
    { code: "VAPN", name: "Vaping not permitted" },
    { code: "VAPP", name: "Vaping permitted without restriction" },
    { code: "VPPD", name: "Vaping permitted in designated area" },
  ],
};

export const substanceAbuseFilters: Record<string, FilterOption[]> = {
  "Type of Care": [
    { code: "SA", name: "Substance use treatment" },
    { code: "DT", name: "Detoxification" },
    { code: "HH", name: "Transitional housing, halfway house, or sober home" },
    { code: "SUMH", name: "Treatment for co-occurring substance use plus serious mental health illness" },
  ],
  "Service Setting": [
    { code: "HI", name: "Hospital inpatient/24-hour hospital inpatient" },
    { code: "OP", name: "Outpatient" },
    { code: "RES", name: "Residential/24-hour residential" },
    { code: "HID", name: "Hospital inpatient detoxification" },
    { code: "HIT", name: "Hospital inpatient treatment" },
    { code: "OD", name: "Outpatient detoxification" },
    { code: "ODT", name: "Outpatient day treatment or partial hospitalization" },
    { code: "OIT", name: "Intensive outpatient treatment" },
    { code: "OMB", name: "Outpatient methadone/buprenorphine or naltrexone treatment" },
    { code: "ORT", name: "Regular outpatient treatment" },
    { code: "RD", name: "Residential detoxification" },
    { code: "RL", name: "Long-term residential" },
    { code: "RS", name: "Short-term residential" },
  ],
  "Hospitals": [
    { code: "GH", name: "General Hospital (including VA hospital)" },
    { code: "PSYH", name: "Psychiatric hospital" },
  ],
  "Opioid Medications": [
    { code: "MU", name: "Methadone used in Treatment" },
    { code: "BU", name: "Buprenorphine used in Treatment" },
    { code: "NU", name: "Naltrexone used in Treatment" },
    { code: "OTP", name: "Federally-certified Opioid Treatment Program" },
    { code: "DB", name: "Buprenorphine detoxification" },
    { code: "BUM", name: "Buprenorphine maintenance" },
    { code: "DM", name: "Methadone detoxification" },
    { code: "MM", name: "Methadone maintenance" },
    { code: "UB", name: "Prescribes buprenorphine" },
    { code: "UN", name: "Prescribes naltrexone" },
    { code: "RPN", name: "Relapse prevention with naltrexone" },
    { code: "PAIN", name: "Use methadone/buprenorphine for pain management" },
    { code: "MOA", name: "Accepts clients using MAT but prescribed elsewhere" },
    { code: "NMOA", name: "Does not use MAT for opioid use disorders" },
    { code: "DLC", name: "Lofexidine or Clonidine detoxification" },
    { code: "MWS", name: "Maintenance with medically supervised withdrawal" },
  ],
  "Treatment Approaches": [
    { code: "ANG", name: "Anger management" },
    { code: "BIA", name: "Brief intervention" },
    { code: "CBT", name: "Cognitive behavioral therapy" },
    { code: "CMI", name: "Contingency management/motivational incentives" },
    { code: "CRV", name: "Community reinforcement plus vouchers" },
    { code: "CFT", name: "Couples/family therapy" },
    { code: "DBT", name: "Dialectical behavior therapy" },
    { code: "GT", name: "Group therapy" },
    { code: "IDD", name: "Integrated Mental and Substance Use Disorder treatment" },
    { code: "IPT", name: "Individual psychotherapy" },
    { code: "MOTI", name: "Motivational interviewing" },
    { code: "MXM", name: "Matrix Model" },
    { code: "RELP", name: "Relapse prevention" },
    { code: "SACA", name: "Substance use disorder counseling" },
    { code: "TRC", name: "Trauma-related counseling" },
    { code: "TELE", name: "Telemedicine/telehealth therapy" },
    { code: "TWFA", name: "12-step facilitation" },
  ],
  "Pharmacotherapies": [
    { code: "ACM", name: "Acamprosate (Campral)" },
    { code: "DSF", name: "Disulfiram" },
    { code: "METH", name: "Methadone" },
    { code: "BSDM", name: "Buprenorphine sub-dermal implant" },
    { code: "BWN", name: "Buprenorphine with naloxone" },
    { code: "BWON", name: "Buprenorphine without naloxone" },
    { code: "BERI", name: "Buprenorphine (extended-release, injectable)" },
    { code: "NXN", name: "Naltrexone (oral)" },
    { code: "VTRL", name: "Naltrexone (extended-release, injectable)" },
    { code: "MHIV", name: "Medications for HIV treatment" },
    { code: "MHCV", name: "Medications for Hepatitis C treatment" },
    { code: "LFXD", name: "Lofexidine" },
    { code: "CLND", name: "Clonidine" },
    { code: "MMD", name: "Medication for mental disorders" },
    { code: "MPEP", name: "Medications for pre-exposure to prophylaxis" },
    { code: "NRT", name: "Nicotine replacement" },
    { code: "NSC", name: "Non-nicotine smoking/tobacco cessation" },
  ],
  "Facility Operation": [
    { code: "LCCG", name: "Local, county, or community government" },
    { code: "DDF", name: "Department of Defense" },
    { code: "IH", name: "Indian Health Services" },
    { code: "PVTP", name: "Private for-profit organization" },
    { code: "PVTN", name: "Private non-profit organization" },
    { code: "STG", name: "State government" },
    { code: "TBG", name: "Tribal government" },
    { code: "FED", name: "Federal Government" },
    { code: "VAMC", name: "U.S. Department of Veterans Affairs" },
  ],
  "Licenses/Certs": [
    { code: "STAG", name: "State Substance use treatment agency" },
    { code: "STMH", name: "State mental health department" },
    { code: "STDH", name: "State department of health" },
    { code: "CARF", name: "Commission on Accreditation of Rehabilitation Facilities (CARF)" },
    { code: "COA", name: "Council on Accreditation (COA)" },
    { code: "HFAP", name: "Healthcare Facilities Accreditation Program (HFAP)" },
    { code: "HLA", name: "Hospital licensing authority" },
    { code: "JC", name: "The Joint Commission" },
    { code: "NCQA", name: "National Committee for Quality Assurance (NCQA)" },
    { code: "FQHC", name: "Federally Qualified Health Center" },
    { code: "SOTP", name: "SAMHSA certification for opioid treatment program (OTP)" },
    { code: "DEA", name: "Drug Enforcement Agency (DEA)" },
  ],
  "Payment Accepted": [
    { code: "FSA", name: "Federal or any government funding for substance use treatment" },
    { code: "ITU", name: "IHS/Tribal/Urban (ITU) funds" },
    { code: "MC", name: "Medicare" },
    { code: "MD", name: "Medicaid" },
    { code: "MI", name: "Federal military insurance (e.g., TRICARE)" },
    { code: "NP", name: "No payment accepted" },
    { code: "PI", name: "Private health insurance" },
    { code: "SF", name: "Cash or self-payment" },
    { code: "SI", name: "State-financed health insurance plan other than Medicaid" },
    { code: "SAMF", name: "SAMHSA funding/block grants" },
  ],
  "Payment Assistance": [
    { code: "PA", name: "Payment assistance (check with facility for details)" },
    { code: "SS", name: "Sliding fee scale (fee is based on income and other factors)" },
  ],
  "Special Programs": [
    { code: "AD", name: "Adolescents" },
    { code: "TAY", name: "Young adults" },
    { code: "WN", name: "Adult women" },
    { code: "PW", name: "Pregnant/postpartum women" },
    { code: "MN", name: "Adult men" },
    { code: "SE", name: "Seniors or older adults" },
    { code: "GL", name: "LGBTQ+" },
    { code: "VET", name: "Veterans" },
    { code: "ADM", name: "Active duty military" },
    { code: "MF", name: "Members of military families" },
    { code: "CJ", name: "Criminal justice (other than DUI/DWI)/Forensic clients" },
    { code: "CO", name: "Clients with co-occurring mental and substance use disorders" },
    { code: "COPSU", name: "Clients with co-occurring pain and substance use disorders" },
    { code: "HV", name: "Clients with HIV or AIDS" },
    { code: "XA", name: "Clients who have experienced sexual abuse" },
    { code: "DV", name: "Clients who have experienced intimate partner violence" },
    { code: "TRMA", name: "Clients who have experienced trauma" },
  ],
  "Assessment": [
    { code: "CMHA", name: "Comprehensive mental health assessment" },
    { code: "CSAA", name: "Comprehensive substance use assessment" },
    { code: "ISC", name: "Interim services for clients" },
    { code: "OPC", name: "Outreach to persons in the community" },
    { code: "MHPA", name: "Complete medical history/physical exam" },
    { code: "STU", name: "Screening for tobacco use" },
    { code: "SSA", name: "Screening for substance use" },
    { code: "SMHD", name: "Screening for mental disorders" },
    { code: "PIEC", name: "Professional interventionist/educational consultant" },
  ],
  "Testing": [
    { code: "BABA", name: "Breathalyzer or blood alcohol testing" },
    { code: "DAOF", name: "Drug and alcohol oral fluid testing" },
    { code: "DAUT", name: "Drug or alcohol urine screening" },
    { code: "HIVT", name: "HIV testing" },
    { code: "STDT", name: "STD testing" },
    { code: "TBS", name: "TB screening" },
    { code: "MST", name: "Metabolic syndrome monitoring" },
    { code: "HBT", name: "Testing for Hepatitis B (HBV)" },
    { code: "HCT", name: "Testing for Hepatitis C (HCV)" },
  ],
  "Ancillary Services": [
    { code: "SHG", name: "Self-help groups" },
    { code: "HS", name: "Housing services" },
    { code: "AOSS", name: "Assistance with obtaining social services" },
    { code: "RC", name: "Recovery coach" },
    { code: "PEER", name: "Mentoring/peer support" },
    { code: "EMP", name: "Employment counseling or training" },
    { code: "TGD", name: "Treatment for gambling disorder" },
    { code: "TOD", name: "Treatment for other addiction disorder" },
    { code: "ACU", name: "Acupuncture" },
    { code: "BC", name: "Residential beds for clients' children" },
    { code: "CM", name: "Case management service" },
    { code: "CCC", name: "Child care for clients' children" },
    { code: "DVFP", name: "Domestic violence services" },
    { code: "EIH", name: "Early intervention for HIV" },
    { code: "MHS", name: "Mental health services" },
    { code: "SSD", name: "Social skills development" },
    { code: "TA", name: "Transportation assistance" },
    { code: "IPC", name: "Integrated primary care services" },
    { code: "SPS", name: "Suicide prevention services" },
  ],
  "Age Groups": [
    { code: "CHLD", name: "Children/Adolescents" },
    { code: "YAD", name: "Young Adults" },
    { code: "ADLT", name: "Adults" },
    { code: "SNR", name: "Seniors" },
  ],
  "Language Services": [
    { code: "SP", name: "Spanish" },
    { code: "AH", name: "Sign language services for the deaf and hard of hearing" },
    { code: "NX", name: "American Indian or Alaska Native languages" },
    { code: "FX", name: "Other languages (excluding Spanish)" },
    { code: "F4", name: "Arabic" },
    { code: "F17", name: "Chinese (any dialect)" },
    { code: "F19", name: "Creole" },
    { code: "F25", name: "Farsi" },
    { code: "F28", name: "French" },
    { code: "F30", name: "German" },
    { code: "F31", name: "Greek" },
    { code: "F35", name: "Hebrew" },
    { code: "F36", name: "Hindi" },
    { code: "F37", name: "Hmong" },
    { code: "F42", name: "Italian" },
    { code: "F43", name: "Japanese" },
    { code: "F47", name: "Korean" },
    { code: "F66", name: "Polish" },
    { code: "F67", name: "Portuguese" },
    { code: "F70", name: "Russian" },
    { code: "F81", name: "Tagalog" },
    { code: "F92", name: "Vietnamese" },
    { code: "N24", name: "Ojibwa" },
    { code: "N40", name: "Yupik" },
  ],
  "Smoking Policy": [
    { code: "SMON", name: "Smoking not permitted" },
    { code: "SMOP", name: "Smoking permitted without restriction" },
    { code: "SMPD", name: "Smoking permitted in designated area" },
    { code: "VAPN", name: "Vaping not permitted" },
    { code: "VAPP", name: "Vaping permitted without restriction" },
    { code: "VPPD", name: "Vaping permitted in designated area" },
  ],
  "Detoxification Services": [
    { code: "ADTX", name: "Alcohol Detoxification" },
    { code: "BDTX", name: "Benzodiazepines Detoxification" },
    { code: "CDTX", name: "Cocaine Detoxification" },
    { code: "MDTX", name: "Methamphetamines detoxification" },
    { code: "ODTX", name: "Opioids detoxification" },
    { code: "MDET", name: "Medication routinely used during detoxification" },
  ],
  "Education Services": [
    { code: "HAEC", name: "HIV or AIDS education, counseling, or support" },
    { code: "TAEC", name: "Hepatitis education, counseling, or support" },
    { code: "HEOH", name: "Health education services other than HIV/AIDS or hepatitis" },
    { code: "SAE", name: "Substance use disorder education" },
    { code: "TCC", name: "Smoking/vaping/tobacco cessation counseling" },
    { code: "ICO", name: "Individual counseling" },
    { code: "GCO", name: "Group counseling" },
    { code: "FCO", name: "Family counseling" },
    { code: "MCO", name: "Marital/couples counseling" },
    { code: "VOC", name: "Vocational training or educational support" },
  ],
};
