// Shared facility data used by both search interface and facility detail pages

export interface Facility {
  id: number
  name1: string
  name2: string
  street1: string
  street2: string
  city: string
  state: string
  zip: string
  phone: string
  intake1: string
  intake2: string
  intake1a: string
  intake2a: string
  // New fields added for demonstration
  county?: string
  website?: string
  latitude?: number
  longitude?: number
  service_code_info: string
  services: string[]
}

export const serviceCategories = {
  "Type of Care": [
    { code: "SA", name: "Substance use treatment", color: "bg-blue-100 text-blue-700" },
    { code: "MH", name: "Mental health treatment", color: "bg-emerald-100 text-emerald-700" },
    { code: "DT", name: "Detoxification", color: "bg-red-100 text-red-700" },
    { code: "HH", name: "Transitional housing, halfway house, or sober home", color: "bg-amber-100 text-amber-700" },
    {
      code: "SUMH",
      name: "Co-occurring substance use plus serious mental health illness",
      color: "bg-purple-100 text-purple-700",
    },
  ],
  "Service Setting": [
    { code: "HI", name: "Hospital inpatient/24-hour hospital inpatient", color: "bg-red-100 text-red-700" },
    { code: "OP", name: "Outpatient", color: "bg-amber-100 text-amber-700" },
    { code: "PHDT", name: "Partial hospitalization/day treatment", color: "bg-orange-100 text-orange-700" },
    { code: "RES", name: "Residential/24-hour residential", color: "bg-teal-100 text-teal-700" },
    { code: "HID", name: "Hospital inpatient detoxification", color: "bg-rose-100 text-rose-700" },
    { code: "HIT", name: "Hospital inpatient treatment", color: "bg-pink-100 text-pink-700" },
    { code: "OD", name: "Outpatient detoxification", color: "bg-orange-100 text-orange-700" },
    {
      code: "ODT",
      name: "Outpatient day treatment or partial hospitalization",
      color: "bg-yellow-100 text-yellow-700",
    },
    { code: "OIT", name: "Intensive outpatient treatment", color: "bg-lime-100 text-lime-700" },
    {
      code: "OMB",
      name: "Outpatient methadone/buprenorphine or naltrexone treatment",
      color: "bg-green-100 text-green-700",
    },
    { code: "ORT", name: "Regular outpatient treatment", color: "bg-emerald-100 text-emerald-700" },
    { code: "RD", name: "Residential detoxification", color: "bg-teal-100 text-teal-700" },
    { code: "RL", name: "Long-term residential", color: "bg-cyan-100 text-cyan-700" },
    { code: "RS", name: "Short-term residential", color: "bg-sky-100 text-sky-700" },
  ],
  "Facility Type": [
    { code: "CMHC", name: "Community mental health center", color: "bg-indigo-100 text-indigo-700" },
    { code: "CBHC", name: "Certified Community Behavioral Health Clinic", color: "bg-cyan-100 text-cyan-700" },
    { code: "MSMH", name: "Multi-setting mental health facility", color: "bg-violet-100 text-violet-700" },
    { code: "OMH", name: "Outpatient mental health facility", color: "bg-sky-100 text-sky-700" },
    { code: "ORES", name: "Other residential treatment facility", color: "bg-rose-100 text-rose-700" },
    { code: "PH", name: "Partial hospitalization/day treatment", color: "bg-pink-100 text-pink-700" },
    { code: "PSY", name: "Psychiatric hospital", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "RTCA", name: "Residential treatment center (RTC) for adults", color: "bg-purple-100 text-purple-700" },
    { code: "RTCC", name: "Residential treatment center (RTC) for children", color: "bg-blue-100 text-blue-700" },
    {
      code: "IPSY",
      name: "Separate inpatient psychiatric unit of a general hospital",
      color: "bg-emerald-100 text-emerald-700",
    },
    { code: "SHP", name: "State hospital", color: "bg-teal-100 text-teal-700" },
    {
      code: "VAHC",
      name: "Veterans Affairs Medical Center or other VA healthcare facility",
      color: "bg-slate-100 text-slate-700",
    },
  ],
  "Treatment Approaches": [
    { code: "AT", name: "Activity therapy", color: "bg-lime-100 text-lime-700" },
    { code: "ANG", name: "Anger management", color: "bg-red-100 text-red-700" },
    { code: "BIA", name: "Brief intervention", color: "bg-orange-100 text-orange-700" },
    { code: "CBT", name: "Cognitive behavioral therapy", color: "bg-green-100 text-green-700" },
    { code: "CMI", name: "Contingency management/motivational incentives", color: "bg-emerald-100 text-emerald-700" },
    { code: "CRT", name: "Cognitive remediation therapy", color: "bg-emerald-100 text-emerald-700" },
    { code: "CRV", name: "Community reinforcement plus vouchers", color: "bg-teal-100 text-teal-700" },
    { code: "CFT", name: "Couples/family therapy", color: "bg-teal-100 text-teal-700" },
    { code: "DBT", name: "Dialectical behavior therapy", color: "bg-cyan-100 text-cyan-700" },
    { code: "ECT", name: "Electroconvulsive therapy", color: "bg-sky-100 text-sky-700" },
    { code: "EMDR", name: "Eye Movement Desensitization and Reprocessing therapy", color: "bg-blue-100 text-blue-700" },
    { code: "GT", name: "Group therapy", color: "bg-indigo-100 text-indigo-700" },
    {
      code: "IDD",
      name: "Integrated Mental and Substance Use Disorder treatment",
      color: "bg-violet-100 text-violet-700",
    },
    { code: "IPT", name: "Individual psychotherapy", color: "bg-purple-100 text-purple-700" },
    { code: "KIT", name: "Ketamine Infusion Therapy", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "MOTI", name: "Motivational interviewing", color: "bg-green-100 text-green-700" },
    { code: "MXM", name: "Matrix Model", color: "bg-cyan-100 text-cyan-700" },
    { code: "RELP", name: "Relapse prevention", color: "bg-sky-100 text-sky-700" },
    { code: "SACA", name: "Substance use disorder counseling", color: "bg-blue-100 text-blue-700" },
    { code: "TMS", name: "Transcranial Magnetic Stimulation", color: "bg-pink-100 text-pink-700" },
    { code: "TRC", name: "Trauma-related counseling", color: "bg-indigo-100 text-indigo-700" },
    { code: "TELE", name: "Telemedicine/telehealth therapy", color: "bg-rose-100 text-rose-700" },
    { code: "TWFA", name: "12-step facilitation", color: "bg-purple-100 text-purple-700" },
  ],
  "Opioid Treatment": [
    { code: "MU", name: "Methadone used in Treatment", color: "bg-pink-100 text-pink-700" },
    { code: "BU", name: "Buprenorphine used in Treatment", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "NU", name: "Naltrexone used in Treatment", color: "bg-purple-100 text-purple-700" },
    { code: "OTP", name: "Federally-certified Opioid Treatment Program", color: "bg-violet-100 text-violet-700" },
    { code: "DB", name: "Buprenorphine detoxification", color: "bg-indigo-100 text-indigo-700" },
    { code: "BUM", name: "Buprenorphine maintenance", color: "bg-blue-100 text-blue-700" },
    { code: "DM", name: "Methadone detoxification", color: "bg-sky-100 text-sky-700" },
    { code: "MM", name: "Methadone maintenance", color: "bg-cyan-100 text-cyan-700" },
    { code: "UB", name: "Prescribes buprenorphine", color: "bg-teal-100 text-teal-700" },
    { code: "UN", name: "Prescribes naltrexone", color: "bg-emerald-100 text-emerald-700" },
    { code: "RPN", name: "Relapse prevention with naltrexone", color: "bg-green-100 text-green-700" },
    { code: "MOA", name: "Accepts clients using MAT but prescribed elsewhere", color: "bg-lime-100 text-lime-700" },
  ],
  "Emergency Services": [
    { code: "CIT", name: "Crisis intervention team", color: "bg-red-100 text-red-700" },
    { code: "PEON", name: "Psychiatric emergency onsite services", color: "bg-orange-100 text-orange-700" },
    { code: "PEOFF", name: "Psychiatric emergency mobile/off-site services", color: "bg-amber-100 text-amber-700" },
    { code: "WI", name: "Psychiatric emergency walk-in services", color: "bg-yellow-100 text-yellow-700" },
  ],
  "Payment Accepted": [
    { code: "CLF", name: "County or local government funds", color: "bg-blue-100 text-blue-700" },
    { code: "CMHG", name: "Community Mental Health Block Grants", color: "bg-indigo-100 text-indigo-700" },
    {
      code: "FSA",
      name: "Federal/government funding for substance use programs",
      color: "bg-violet-100 text-violet-700",
    },
    { code: "ITU", name: "IHS/Tribal/Urban (ITU) funds", color: "bg-purple-100 text-purple-700" },
    { code: "MC", name: "Medicare", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "MD", name: "Medicaid", color: "bg-pink-100 text-pink-700" },
    { code: "MI", name: "Federal military insurance (TRICARE)", color: "bg-rose-100 text-rose-700" },
    { code: "PI", name: "Private health insurance", color: "bg-amber-100 text-amber-700" },
    { code: "SF", name: "Cash or self-payment", color: "bg-orange-100 text-orange-700" },
    {
      code: "SI",
      name: "State-financed health insurance plan other than Medicaid",
      color: "bg-yellow-100 text-yellow-700",
    },
    { code: "SS", name: "Sliding fee scale", color: "bg-lime-100 text-lime-700" },
    { code: "SAMF", name: "SAMHSA funding/block grants", color: "bg-green-100 text-green-700" },
    { code: "PA", name: "Payment assistance", color: "bg-emerald-100 text-emerald-700" },
    { code: "VAF", name: "U.S. Department of VA funds", color: "bg-slate-100 text-slate-700" },
  ],
  "Special Programs": [
    { code: "AD", name: "Adolescents", color: "bg-amber-100 text-amber-700" },
    { code: "TAY", name: "Young adults", color: "bg-orange-100 text-orange-700" },
    { code: "WN", name: "Adult women", color: "bg-yellow-100 text-yellow-700" },
    { code: "PW", name: "Pregnant/postpartum women", color: "bg-lime-100 text-lime-700" },
    { code: "MN", name: "Adult men", color: "bg-green-100 text-green-700" },
    { code: "SE", name: "Seniors or older adults", color: "bg-emerald-100 text-emerald-700" },
    { code: "GL", name: "LGBTQ", color: "bg-teal-100 text-teal-700" },
    { code: "VET", name: "Veterans", color: "bg-cyan-100 text-cyan-700" },
    { code: "ADM", name: "Active duty military", color: "bg-sky-100 text-sky-700" },
    { code: "CJ", name: "Criminal justice/Forensic clients", color: "bg-blue-100 text-blue-700" },
    { code: "CO", name: "Co-occurring mental and substance use disorders", color: "bg-indigo-100 text-indigo-700" },
    { code: "COPSU", name: "Co-occurring pain and substance use disorders", color: "bg-violet-100 text-violet-700" },
    { code: "HV", name: "Clients with HIV or AIDS", color: "bg-purple-100 text-purple-700" },
    { code: "DV", name: "Domestic violence", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "TRMA", name: "Clients who have experienced trauma", color: "bg-pink-100 text-pink-700" },
    { code: "PTSD", name: "Post-traumatic stress disorder (PTSD)", color: "bg-rose-100 text-rose-700" },
    { code: "SED", name: "Children/adolescents with serious emotional disturbance", color: "bg-red-100 text-red-700" },
    { code: "SMI", name: "Persons 18+ with serious mental illness", color: "bg-orange-100 text-orange-700" },
  ],
  "Age Groups": [
    { code: "CHLD", name: "Children/Adolescents", color: "bg-amber-100 text-amber-700" },
    { code: "YAD", name: "Young Adults", color: "bg-orange-100 text-orange-700" },
    { code: "ADLT", name: "Adults", color: "bg-yellow-100 text-yellow-700" },
    { code: "SNR", name: "Seniors", color: "bg-lime-100 text-lime-700" },
  ],
  "Language Services": [
    { code: "SP", name: "Spanish", color: "bg-blue-100 text-blue-700" },
    { code: "ASL", name: "American Sign Language (ASL)", color: "bg-indigo-100 text-indigo-700" },
    { code: "OL", name: "Other Languages", color: "bg-violet-100 text-violet-700" },
  ],
  "Detoxification Services": [
    { code: "ALCD", name: "Alcohol detoxification", color: "bg-red-100 text-red-700" },
    { code: "BENZD", name: "Benzodiazepines detoxification", color: "bg-orange-100 text-orange-700" },
    { code: "COCD", name: "Cocaine detoxification", color: "bg-amber-100 text-amber-700" },
    { code: "METHD", name: "Methamphetamine detoxification", color: "bg-yellow-100 text-yellow-700" },
    { code: "OPD", name: "Opioid detoxification", color: "bg-lime-100 text-lime-700" },
  ],
  "Ancillary Services": [
    { code: "SHG", name: "Self-help groups", color: "bg-lime-100 text-lime-700" },
    { code: "HS", name: "Housing services", color: "bg-green-100 text-green-700" },
    { code: "AOSS", name: "Assistance with obtaining social services", color: "bg-emerald-100 text-emerald-700" },
    { code: "RC", name: "Recovery coach", color: "bg-teal-100 text-teal-700" },
    { code: "PEER", name: "Mentoring/peer support", color: "bg-cyan-100 text-cyan-700" },
    { code: "EMP", name: "Employment counseling or training", color: "bg-sky-100 text-sky-700" },
    { code: "TCC", name: "Smoking/vaping/tobacco cessation counseling", color: "bg-blue-100 text-blue-700" },
    { code: "CM", name: "Case management", color: "bg-indigo-100 text-indigo-700" },
    { code: "SC", name: "Social skills development", color: "bg-violet-100 text-violet-700" },
    { code: "EDU", name: "Education services", color: "bg-purple-100 text-purple-700" },
    { code: "TRANS", name: "Transportation assistance", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "CHILD", name: "Childcare services", color: "bg-pink-100 text-pink-700" },
  ],
  "Licenses/Certs": [
    { code: "FQHC", name: "Federally Qualified Health Center", color: "bg-sky-100 text-sky-700" },
    { code: "MHC", name: "Mental health clinic or mental health center", color: "bg-blue-100 text-blue-700" },
    { code: "JCAH", name: "Joint Commission accreditation", color: "bg-indigo-100 text-indigo-700" },
    { code: "CARF", name: "CARF accreditation", color: "bg-violet-100 text-violet-700" },
    { code: "COLA", name: "COLA accreditation", color: "bg-purple-100 text-purple-700" },
    { code: "NCQA", name: "NCQA accreditation", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "SLIC", name: "State license", color: "bg-pink-100 text-pink-700" },
    { code: "DHHS", name: "HHS certification", color: "bg-rose-100 text-rose-700" },
    { code: "AOA", name: "AOA Healthcare Facilities accreditation", color: "bg-red-100 text-red-700" },
  ],
  "Facility Operation": [
    { code: "PR", name: "Private for-profit organization", color: "bg-amber-100 text-amber-700" },
    { code: "PNP", name: "Private non-profit organization", color: "bg-yellow-100 text-yellow-700" },
    { code: "LGV", name: "Local, county, or community government", color: "bg-lime-100 text-lime-700" },
    { code: "SGV", name: "State government", color: "bg-green-100 text-green-700" },
    { code: "FGV", name: "Federal government", color: "bg-emerald-100 text-emerald-700" },
    { code: "TB", name: "Tribal government", color: "bg-teal-100 text-teal-700" },
  ],
  Assessment: [
    { code: "COMP", name: "Comprehensive mental health assessment", color: "bg-cyan-100 text-cyan-700" },
    { code: "DIAG", name: "Diagnostic evaluation", color: "bg-sky-100 text-sky-700" },
    { code: "SCRN", name: "Screening for mental health disorders", color: "bg-blue-100 text-blue-700" },
    { code: "SBIRT", name: "SBIRT screening", color: "bg-indigo-100 text-indigo-700" },
    { code: "LSI", name: "Lab testing/screening/intake", color: "bg-violet-100 text-violet-700" },
  ],
  Testing: [
    { code: "DRUG", name: "Drug or alcohol urine screening", color: "bg-purple-100 text-purple-700" },
    { code: "STD", name: "STD testing", color: "bg-fuchsia-100 text-fuchsia-700" },
    { code: "TB", name: "TB screening", color: "bg-pink-100 text-pink-700" },
    { code: "HIV", name: "HIV testing", color: "bg-rose-100 text-rose-700" },
    { code: "HEPC", name: "Hepatitis C testing", color: "bg-red-100 text-red-700" },
    { code: "HEPB", name: "Hepatitis B testing", color: "bg-orange-100 text-orange-700" },
  ],
  "Smoking Policy": [
    { code: "SNP", name: "Smoking not permitted", color: "bg-amber-100 text-amber-700" },
    { code: "SDA", name: "Smoking permitted in designated areas", color: "bg-yellow-100 text-yellow-700" },
    { code: "SPO", name: "Smoking permitted without restriction", color: "bg-lime-100 text-lime-700" },
  ],
}

export const facilities: Facility[] = [
  {
    id: 1,
    name1: "Arizona Behavioral Health Center",
    name2: "ABHC Phoenix Campus",
    street1: "1234 Health Avenue",
    street2: "Suite 100",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    county: "Maricopa",
    phone: "(602) 555-0123",
    intake1: "(602) 555-0124",
    intake1a: "24/7 Hotline",
    intake2: "",
    intake2a: "",
    website: "https://azbehavioralhealth.example.com",
    latitude: 33.4484,
    longitude: -112.074,
    services: [
      // Type of Care
      "MH",
      "SA",
      "DT",
      "SUMH",
      // Service Setting
      "OP",
      "HI",
      "RES",
      "PHDT",
      "OIT",
      "ORT",
      // Facility Type
      "CMHC",
      "CBHC",
      // Treatment Approaches
      "CBT",
      "DBT",
      "GT",
      "IPT",
      "MOTI",
      "TWFA",
      "TRC",
      "TELE",
      "EMDR",
      "CFT",
      "RELP",
      // Opioid Treatment
      "BU",
      "NU",
      "BUM",
      // Emergency Services
      "CIT",
      "WI",
      "PEON",
      // Payment Accepted
      "MC",
      "MD",
      "PI",
      "SF",
      "SS",
      "PA",
      // Special Programs
      "AD",
      "TAY",
      "WN",
      "MN",
      "SE",
      "VET",
      "GL",
      "CO",
      "TRMA",
      "PTSD",
      // Age Groups
      "CHLD",
      "YAD",
      "ADLT",
      "SNR",
      // Language Services
      "SP",
      "ASL",
      // Ancillary Services
      "SHG",
      "HS",
      "RC",
      "PEER",
      "EMP",
      "CM",
      "SC",
      "EDU",
      "TRANS",
      // Licenses/Certs
      "JCAH",
      "SLIC",
      "MHC",
      // Assessment
      "COMP",
      "DIAG",
      "SCRN",
      // Testing
      "DRUG",
      "HIV",
      "HEPC",
      // Smoking Policy
      "SNP",
    ],
    service_code_info:
      "Comprehensive behavioral health services including mental health treatment, substance use treatment, and co-occurring disorder services. We offer a full continuum of care from outpatient to residential programs.",
  },
  {
    id: 2,
    name1: "Tucson Community Healing",
    name2: "Recovery Services Division",
    street1: "567 Recovery Boulevard",
    street2: "",
    city: "Tucson",
    state: "AZ",
    zip: "85701",
    phone: "(520) 555-0456",
    intake1: "(520) 555-0457",
    intake2: "",
    intake1a: "24/7",
    intake2a: "",
    service_code_info:
      "Specialized substance abuse treatment center offering detoxification, residential treatment, and outpatient services.",
    services: ["SA", "DT", "RES", "MOTI", "TWFA", "SF", "SS"],
  },
  {
    id: 3,
    name1: "Mesa Family Wellness Center",
    name2: "",
    street1: "890 Wellness Way",
    street2: "Building B",
    city: "Mesa",
    state: "AZ",
    zip: "85201",
    phone: "(480) 555-0789",
    intake1: "(480) 555-0790",
    intake2: "(480) 555-0791",
    intake1a: "Mon-Sat 9AM-7PM",
    intake2a: "Spanish Line Available",
    service_code_info:
      "Family-centered mental health facility specializing in outpatient services, couples and family therapy.",
    services: ["MH", "OP", "CFT", "IPT", "GT", "SP"],
  },
  {
    id: 4,
    name1: "Scottsdale Recovery Center",
    name2: "Opioid Treatment Program",
    street1: "234 Hope Street",
    street2: "",
    city: "Scottsdale",
    state: "AZ",
    zip: "85251",
    phone: "(480) 555-1234",
    intake1: "(480) 555-1235",
    intake2: "",
    intake1a: "24/7",
    intake2a: "",
    service_code_info: "Federally-certified Opioid Treatment Program providing medication-assisted treatment.",
    services: ["SA", "OTP", "MU", "BU", "NU", "RES", "RELP"],
  },
  {
    id: 5,
    name1: "Flagstaff Mental Health Services",
    name2: "Northern Arizona Psychiatric Center",
    street1: "456 Mountain View Drive",
    street2: "Floor 3",
    city: "Flagstaff",
    state: "AZ",
    zip: "86001",
    phone: "(928) 555-5678",
    intake1: "(928) 555-5679",
    intake2: "(928) 555-5680",
    intake1a: "Mon-Fri 8AM-6PM",
    intake2a: "Crisis: 24/7",
    service_code_info:
      "Full-service psychiatric facility offering inpatient hospitalization, outpatient services, and crisis intervention.",
    services: ["MH", "HI", "OP", "PSY", "DBT", "CBT", "ECT"],
  },
  {
    id: 6,
    name1: "Tempe Youth Services",
    name2: "Adolescent Treatment Center",
    street1: "789 College Avenue",
    street2: "",
    city: "Tempe",
    state: "AZ",
    zip: "85281",
    phone: "(480) 555-2345",
    intake1: "(480) 555-2346",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info:
      "Specialized treatment center for adolescents and young adults with mental health and substance use challenges.",
    services: ["MH", "SA", "OP", "AD", "TAY", "CHLD", "GT"],
  },
  {
    id: 7,
    name1: "Chandler Wellness Institute",
    name2: "",
    street1: "321 Innovation Way",
    street2: "Suite 200",
    city: "Chandler",
    state: "AZ",
    zip: "85224",
    phone: "(480) 555-3456",
    intake1: "(480) 555-3457",
    intake2: "",
    intake1a: "Mon-Sat 8AM-8PM",
    intake2a: "",
    service_code_info:
      "Modern wellness facility offering innovative mental health treatments including TMS and ketamine therapy.",
    services: ["MH", "OP", "TMS", "KIT", "CBT", "TELE", "PI"],
  },
  {
    id: 8,
    name1: "Gilbert Family Counseling",
    name2: "East Valley Mental Health",
    street1: "654 Family Lane",
    street2: "",
    city: "Gilbert",
    state: "AZ",
    zip: "85234",
    phone: "(480) 555-4567",
    intake1: "(480) 555-4568",
    intake2: "",
    intake1a: "Mon-Fri 9AM-6PM",
    intake2a: "",
    service_code_info: "Family-focused counseling center providing individual, couples, and family therapy services.",
    services: ["MH", "OP", "CFT", "IPT", "DV", "TRMA", "MD"],
  },
  {
    id: 9,
    name1: "Glendale Recovery House",
    name2: "Residential Treatment Facility",
    street1: "987 Serenity Circle",
    street2: "",
    city: "Glendale",
    state: "AZ",
    zip: "85301",
    phone: "(623) 555-5678",
    intake1: "(623) 555-5679",
    intake2: "(623) 555-5680",
    intake1a: "24/7",
    intake2a: "",
    service_code_info:
      "Long-term residential treatment facility for substance abuse recovery with comprehensive support services.",
    services: ["SA", "RES", "RL", "TWFA", "MOTI", "HH", "SS"],
  },
  {
    id: 10,
    name1: "Peoria Psychiatric Center",
    name2: "",
    street1: "147 Healthcare Drive",
    street2: "Building A",
    city: "Peoria",
    state: "AZ",
    zip: "85345",
    phone: "(623) 555-6789",
    intake1: "(623) 555-6790",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info: "Comprehensive psychiatric care center offering medication management and therapy services.",
    services: ["MH", "OP", "CMHC", "IPT", "MC", "MD", "PI"],
  },
  {
    id: 11,
    name1: "Surprise Counseling Services",
    name2: "West Valley Behavioral Health",
    street1: "258 Sunset Boulevard",
    street2: "",
    city: "Surprise",
    state: "AZ",
    zip: "85374",
    phone: "(623) 555-7890",
    intake1: "(623) 555-7891",
    intake2: "",
    intake1a: "Mon-Sat 9AM-7PM",
    intake2a: "",
    service_code_info:
      "Community behavioral health center serving the West Valley with accessible mental health services.",
    services: ["MH", "OP", "CBHC", "GT", "CBT", "SS", "PA"],
  },
  {
    id: 12,
    name1: "Yuma Crisis Center",
    name2: "Southwest Arizona Mental Health",
    street1: "369 Desert View Road",
    street2: "",
    city: "Yuma",
    state: "AZ",
    zip: "85364",
    phone: "(928) 555-8901",
    intake1: "(928) 555-8902",
    intake2: "(928) 555-8903",
    intake1a: "24/7",
    intake2a: "Crisis Line",
    service_code_info: "24/7 crisis intervention center providing emergency psychiatric services and stabilization.",
    services: ["MH", "CIT", "PEON", "WI", "HI", "MC", "MD"],
  },
  {
    id: 13,
    name1: "Prescott Valley Recovery",
    name2: "Mountain View Treatment Center",
    street1: "741 Pine Street",
    street2: "",
    city: "Prescott Valley",
    state: "AZ",
    zip: "86314",
    phone: "(928) 555-9012",
    intake1: "(928) 555-9013",
    intake2: "",
    intake1a: "Mon-Fri 8AM-6PM",
    intake2a: "",
    service_code_info: "Scenic recovery center offering substance abuse treatment in a peaceful mountain setting.",
    services: ["SA", "RES", "RS", "ALCD", "OPD", "TWFA", "VET"],
  },
  {
    id: 14,
    name1: "Goodyear Health Center",
    name2: "Estrella Behavioral Services",
    street1: "852 Palm Lane",
    street2: "Suite 150",
    city: "Goodyear",
    state: "AZ",
    zip: "85338",
    phone: "(623) 555-0124",
    intake1: "(623) 555-0125",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info: "Community health center providing integrated behavioral health and primary care services.",
    services: ["MH", "OP", "OMH", "IPT", "TELE", "SP", "PI"],
  },
  {
    id: 15,
    name1: "Buckeye Treatment Facility",
    name2: "",
    street1: "963 Western Avenue",
    street2: "",
    city: "Buckeye",
    state: "AZ",
    zip: "85326",
    phone: "(623) 555-1235",
    intake1: "(623) 555-1236",
    intake2: "",
    intake1a: "Mon-Sat 8AM-6PM",
    intake2a: "",
    service_code_info: "Outpatient treatment facility specializing in substance abuse and co-occurring disorders.",
    services: ["SA", "OP", "SUMH", "CO", "MOTI", "RELP", "SS"],
  },
  {
    id: 16,
    name1: "Avondale Family Services",
    name2: "Southwest Family Counseling",
    street1: "159 Community Drive",
    street2: "",
    city: "Avondale",
    state: "AZ",
    zip: "85323",
    phone: "(623) 555-2346",
    intake1: "(623) 555-2347",
    intake2: "",
    intake1a: "Mon-Fri 9AM-7PM",
    intake2a: "",
    service_code_info: "Family-oriented counseling center with bilingual services and sliding fee scale.",
    services: ["MH", "OP", "CFT", "CHLD", "SP", "SS", "MD"],
  },
  {
    id: 17,
    name1: "Sierra Vista Veterans Center",
    name2: "Cochise County VA Services",
    street1: "753 Military Highway",
    street2: "",
    city: "Sierra Vista",
    state: "AZ",
    zip: "85635",
    phone: "(520) 555-3457",
    intake1: "(520) 555-3458",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info:
      "Veteran-focused mental health center providing specialized care for military personnel and veterans.",
    services: ["MH", "VAHC", "VET", "ADM", "PTSD", "VAF", "MI"],
  },
  {
    id: 18,
    name1: "Casa Grande Detox Center",
    name2: "Pinal County Recovery Services",
    street1: "357 Recovery Road",
    street2: "",
    city: "Casa Grande",
    state: "AZ",
    zip: "85122",
    phone: "(520) 555-4568",
    intake1: "(520) 555-4569",
    intake2: "(520) 555-4570",
    intake1a: "24/7",
    intake2a: "",
    service_code_info: "Medical detoxification center providing safe withdrawal management and stabilization services.",
    services: ["SA", "DT", "HID", "ALCD", "OPD", "BENZD", "MC"],
  },
  {
    id: 19,
    name1: "Lake Havasu Wellness",
    name2: "Western Arizona Mental Health",
    street1: "951 Lakeview Drive",
    street2: "",
    city: "Lake Havasu City",
    state: "AZ",
    zip: "86403",
    phone: "(928) 555-5679",
    intake1: "(928) 555-5680",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info: "Community wellness center offering mental health services to the Lake Havasu region.",
    services: ["MH", "OP", "GT", "IPT", "SE", "SNR", "MC"],
  },
  {
    id: 20,
    name1: "Kingman Recovery Center",
    name2: "Mohave County Treatment Services",
    street1: "246 Route 66",
    street2: "",
    city: "Kingman",
    state: "AZ",
    zip: "86401",
    phone: "(928) 555-6790",
    intake1: "(928) 555-6791",
    intake2: "",
    intake1a: "Mon-Sat 8AM-6PM",
    intake2a: "",
    service_code_info:
      "Rural recovery center providing accessible substance abuse treatment to Mohave County residents.",
    services: ["SA", "OP", "RES", "METHD", "OPD", "CJ", "SS"],
  },
  {
    id: 21,
    name1: "Oro Valley Psychiatric Associates",
    name2: "",
    street1: "684 Oracle Road",
    street2: "Suite 300",
    city: "Oro Valley",
    state: "AZ",
    zip: "85737",
    phone: "(520) 555-7891",
    intake1: "(520) 555-7892",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info: "Private psychiatric practice offering comprehensive medication management and therapy.",
    services: ["MH", "OP", "IPT", "CBT", "EMDR", "PI", "ADLT"],
  },
  {
    id: 22,
    name1: "Maricopa Integrated Health",
    name2: "Ak-Chin Community Services",
    street1: "147 Tribal Road",
    street2: "",
    city: "Maricopa",
    state: "AZ",
    zip: "85139",
    phone: "(520) 555-8902",
    intake1: "(520) 555-8903",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info: "Integrated health facility serving the Ak-Chin community with culturally sensitive care.",
    services: ["MH", "SA", "OP", "ITU", "GT", "TRMA", "OL"],
  },
  {
    id: 23,
    name1: "Queen Creek Counseling",
    name2: "East Valley Outpatient Services",
    street1: "528 Ellsworth Road",
    street2: "",
    city: "Queen Creek",
    state: "AZ",
    zip: "85142",
    phone: "(480) 555-9013",
    intake1: "(480) 555-9014",
    intake2: "",
    intake1a: "Mon-Sat 8AM-7PM",
    intake2a: "",
    service_code_info: "Growing community counseling center offering individual and family therapy services.",
    services: ["MH", "OP", "CFT", "IPT", "YAD", "ADLT", "PI"],
  },
  {
    id: 24,
    name1: "San Tan Valley Mental Health",
    name2: "Pinal County Behavioral Services",
    street1: "369 Hunt Highway",
    street2: "",
    city: "San Tan Valley",
    state: "AZ",
    zip: "85143",
    phone: "(480) 555-0135",
    intake1: "(480) 555-0136",
    intake2: "",
    intake1a: "Mon-Fri 8AM-6PM",
    intake2a: "",
    service_code_info: "Community mental health center serving the rapidly growing San Tan Valley area.",
    services: ["MH", "OP", "CMHC", "GT", "CBT", "SS", "MD"],
  },
  {
    id: 25,
    name1: "Apache Junction Treatment",
    name2: "Superstition Mountain Recovery",
    street1: "741 Apache Trail",
    street2: "",
    city: "Apache Junction",
    state: "AZ",
    zip: "85120",
    phone: "(480) 555-1246",
    intake1: "(480) 555-1247",
    intake2: "",
    intake1a: "Mon-Sat 8AM-6PM",
    intake2a: "",
    service_code_info: "Substance abuse treatment center with stunning desert mountain views and holistic approach.",
    services: ["SA", "OP", "RES", "AT", "MOTI", "TWFA", "SF"],
  },
  {
    id: 26,
    name1: "Nogales Border Health",
    name2: "Santa Cruz County Services",
    street1: "852 International Street",
    street2: "",
    city: "Nogales",
    state: "AZ",
    zip: "85621",
    phone: "(520) 555-2357",
    intake1: "(520) 555-2358",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info:
      "Bilingual behavioral health center serving the border community with culturally appropriate care.",
    services: ["MH", "SA", "OP", "SP", "TRMA", "SS", "CLF"],
  },
  {
    id: 27,
    name1: "Sedona Healing Center",
    name2: "Red Rock Wellness",
    street1: "963 Red Rock Drive",
    street2: "",
    city: "Sedona",
    state: "AZ",
    zip: "86336",
    phone: "(928) 555-3468",
    intake1: "(928) 555-3469",
    intake2: "",
    intake1a: "Mon-Sun 9AM-6PM",
    intake2a: "",
    service_code_info: "Holistic healing center combining traditional therapy with alternative wellness approaches.",
    services: ["MH", "OP", "AT", "GT", "EMDR", "TELE", "PI"],
  },
  {
    id: 28,
    name1: "Cottonwood Family Center",
    name2: "Verde Valley Behavioral Health",
    street1: "159 Main Street",
    street2: "",
    city: "Cottonwood",
    state: "AZ",
    zip: "86326",
    phone: "(928) 555-4579",
    intake1: "(928) 555-4580",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info: "Community-based family counseling center serving the Verde Valley region.",
    services: ["MH", "OP", "CFT", "CHLD", "AD", "DV", "SS"],
  },
  {
    id: 29,
    name1: "Payson Mountain Recovery",
    name2: "Rim Country Treatment Services",
    street1: "357 Beeline Highway",
    street2: "",
    city: "Payson",
    state: "AZ",
    zip: "85541",
    phone: "(928) 555-5680",
    intake1: "(928) 555-5681",
    intake2: "",
    intake1a: "Mon-Sat 8AM-6PM",
    intake2a: "",
    service_code_info: "Mountain retreat-style recovery center offering peaceful environment for healing.",
    services: ["SA", "RES", "RS", "TWFA", "AT", "VET", "SF"],
  },
  {
    id: 30,
    name1: "Show Low Behavioral Services",
    name2: "White Mountain Mental Health",
    street1: "753 Deuce of Clubs",
    street2: "",
    city: "Show Low",
    state: "AZ",
    zip: "85901",
    phone: "(928) 555-6791",
    intake1: "(928) 555-6792",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info: "Rural behavioral health center serving the White Mountain communities.",
    services: ["MH", "SA", "OP", "CMHC", "GT", "CLF", "MD"],
  },
  {
    id: 31,
    name1: "Bullhead City Wellness",
    name2: "Mohave Valley Health Services",
    street1: "246 Highway 95",
    street2: "",
    city: "Bullhead City",
    state: "AZ",
    zip: "86442",
    phone: "(928) 555-7902",
    intake1: "(928) 555-7903",
    intake2: "",
    intake1a: "Mon-Sat 8AM-6PM",
    intake2a: "",
    service_code_info: "Community wellness center providing comprehensive behavioral health services.",
    services: ["MH", "OP", "GT", "IPT", "SE", "TELE", "SS"],
  },
  {
    id: 32,
    name1: "Safford Regional Mental Health",
    name2: "Graham County Services",
    street1: "684 Main Street",
    street2: "",
    city: "Safford",
    state: "AZ",
    zip: "85546",
    phone: "(928) 555-8013",
    intake1: "(928) 555-8014",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info: "Regional mental health center serving Graham and Greenlee counties.",
    services: ["MH", "OP", "CMHC", "CBT", "IPT", "CLF", "MD"],
  },
  {
    id: 33,
    name1: "Globe-Miami Recovery",
    name2: "Copper Corridor Treatment",
    street1: "147 Broad Street",
    street2: "",
    city: "Globe",
    state: "AZ",
    zip: "85501",
    phone: "(928) 555-9124",
    intake1: "(928) 555-9125",
    intake2: "",
    intake1a: "Mon-Sat 9AM-5PM",
    intake2a: "",
    service_code_info: "Substance abuse recovery center serving the historic Copper Corridor mining communities.",
    services: ["SA", "OP", "MOTI", "RELP", "TWFA", "CJ", "SS"],
  },
  {
    id: 34,
    name1: "Winslow Community Health",
    name2: "Little Colorado Behavioral Services",
    street1: "528 Route 66",
    street2: "",
    city: "Winslow",
    state: "AZ",
    zip: "86047",
    phone: "(928) 555-0235",
    intake1: "(928) 555-0236",
    intake2: "",
    intake1a: "Mon-Fri 8AM-5PM",
    intake2a: "",
    service_code_info: "Community health center providing behavioral health services along the Route 66 corridor.",
    services: ["MH", "SA", "OP", "ITU", "OL", "CLF", "CMHG"],
  },
  {
    id: 35,
    name1: "Page Northern Arizona Center",
    name2: "Lake Powell Wellness",
    street1: "369 Lake Powell Boulevard",
    street2: "",
    city: "Page",
    state: "AZ",
    zip: "86040",
    phone: "(928) 555-1346",
    intake1: "(928) 555-1347",
    intake2: "",
    intake1a: "Mon-Fri 9AM-5PM",
    intake2a: "",
    service_code_info: "Northern Arizona wellness center serving Page and surrounding tribal communities.",
    services: ["MH", "OP", "ITU", "GT", "TRMA", "OL", "CLF"],
  },
]

// Helper function to get facility by ID
export function getFacilityById(id: string | number): Facility | undefined {
  const numId = typeof id === "string" ? Number.parseInt(id, 10) : id
  return facilities.find((f) => f.id === numId)
}

// Helper function to get service info by code
export function getServiceInfo(code: string) {
  for (const [category, services] of Object.entries(serviceCategories)) {
    const service = services.find((s) => s.code === code)
    if (service) return { ...service, category }
  }
  return { code, name: code, color: "bg-gray-100 text-gray-700", category: "Other" }
}
